<template>
  <div class="page"><header class="page-header"><div><div class="eyebrow">Workspace</div><h1 class="page-title">My tasks</h1><p class="page-subtitle">Keep your assignments moving without losing the big picture.</p></div><div class="header-actions"><button v-if="canCreate" class="primary-button" @click="router.push('/tasks/new')">+ New task</button></div></header>
    <div class="toolbar"><div class="search-box"><input v-model="search" placeholder="Search tasks…"/></div><select class="filter" v-model="status"><option value="ALL">All status</option><option value="PENDING">Pending</option><option value="IN_PROGRESS">In progress</option><option value="COMPLETED">Completed</option></select><select class="filter" v-model="priority"><option value="ALL">All priority</option><option value="HIGH">High</option><option value="MEDIUM">Medium</option><option value="LOW">Low</option></select></div>
    <div class="card table-card"><table class="table"><thead><tr><th>Task</th><th>Priority</th><th>Status</th><th>Due date</th><th>Progress</th><th></th></tr></thead><tbody><tr v-for="task in filtered" :key="task.id"><td><div class="task-name"><span class="task-square">✓</span><div><strong>{{task.title}}</strong><span>{{task.description||'No description'}}</span></div></div></td><td><span class="priority-badge" :class="task.priority.toLowerCase()">{{task.priority}}</span></td><td><span class="status-badge" :class="task.status.toLowerCase()">{{pretty(task.status)}}</span></td><td class="date">{{formatDate(task.endDate)}}</td><td><div style="min-width:90px"><div class="progress-track"><div class="progress-fill" :style="{width:(task.progress||0)+'%'}"></div></div><small class="muted">{{task.progress||0}}%</small></div></td><td><button class="view-btn" @click="router.push('/tasks/'+task.id)">Open</button></td></tr></tbody></table><div v-if="!filtered.length" class="empty"><strong>No matching tasks</strong><span>Try changing your search or filters.</span></div></div>
  </div>
</template>
<script setup>
import {ref,computed,onMounted} from 'vue';import {useRouter} from 'vue-router';import api from '../services/api';const router=useRouter(),tasks=ref([]),search=ref(''),status=ref('ALL'),priority=ref('ALL'),canCreate=['ADMIN','MANAGER'].includes(localStorage.getItem('role'));const pretty=s=>s?.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase())||'';const formatDate=d=>d?new Date(d).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'—';const filtered=computed(()=>tasks.value.filter(t=>(!search.value||t.title.toLowerCase().includes(search.value.toLowerCase()))&&(status.value==='ALL'||t.status===status.value)&&(priority.value==='ALL'||t.priority===priority.value)));onMounted(async()=>{try{tasks.value=(await api.get('/tasks')).data||[]}catch(e){console.error(e)}})
</script>
